### ISSUE TITLE
Missing Deprecations

### ISSUE THREAD

**Issue by QuinnyPig** [SummitRoute/aws_breaking_changes#108]
Cognito Sync (https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-sync.html) pushes people to AppSync instead.

Alexa for Business used to be a full fledged AWS service (and showed up on the bill); it got whacked: https://web.archive.org/web/20221225182801/https://docs.aws.amazon.com/a4b/latest/ag/what-is.html

Their Elastic Graphics offering now silently redirects: https://aws.amazon.com/ec2/elastic-graphics/

CloudEndure Migration went EOL: https://docs.cloudendure.com/Content/Configuring_and_Running_Migration/Migration_EOL/Migration_EOL.htm

Proton isn't dead but may as well be: https://github.com/aws/aws-proton-public-roadmap

Honeycode rather famously and loudly got the axe.

The GoLang runtime got whacked: https://aws.amazon.com/blogs/compute/migrating-aws-lambda-functions-from-the-go1-x-runtime-to-the-custom-runtime-on-amazon-linux-2/

Elastic inference isn't available to new customers: https://aws.amazon.com/machine-learning/elastic-inference/

Pepperidge Farm remembers Import/Export jobs: https://aws.amazon.com/about-aws/whats-new/2009/05/20/AWS-Import-Export/

WorkLink got silently redirected: https://aws.amazon.com/about-aws/whats-new/2019/01/introducing-amazon-worklink/

"You forgot Sumerian."  https://aws.amazon.com/blogs/aws/launch-presenting-amazon-sumerian/

Lumberyard may be most famous for its "zombie clause" in the ToS.  https://aws.amazon.com/lumberyard/

RDS on VMware got violently redirected to RDS; they tried to memory hole it. But it went GA! https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-rds-on-vmware-is-now-generally-available/

CodeStar was vanished: https://aws.amazon.com/blogs/aws/new-aws-codestar/

**Comment by 0xdabbad00** [comment]
Thank you @QuinnyPig ! 

Notes on these:
- Cognito Sync: This does appear deprecated, but frustratingly it doesn't provide dates such as when it might be inaccessible.  I've added a new list to the page for services in this state. 
- Alexa for Business: Already on the archive page.
- Elastic Graphics : Already on the archive page.
- CloudEndure migration: Added
- Proton: Not being actively developed doesn't meet my personal criteria for it being deprecated.  I view something as deprecated when the service can no longer be used, or is otherwise degraded.
- Honeycode: Already on the archive page.
- Golang: Good call.  I did add the deprecation of the Python 2.7 SDK, so I feel obligated to add this, although I don't want to add other non-service things.
- Elastic inference: Already on the archive page.
- Import/Export: Added to the archive page.  Appears to have been erased in October 2016 based on archive.org's last capture before the link to https://aws.amazon.com/importexport 301'd.
- Worklink: Added. Appears to have been erased between April and June of 2022. 
- Sumerian: Already on the archive page.
- Lumberyard: Added, and gave it a date of July 2021.
- RDS on VMware: Added.  That's a weird one as they even redirected this blog: https://aws.amazon.com/blogs/database/getting-started-with-amazon-rds-managed-databases-in-your-on-premises-vmware-environment/, so I'll give it a date of the last archive of that blog post, which is March 2022. 
- CodeStar: Already there.
