### ISSUE TITLE
expose this information as an Atom/RSS feed

### ISSUE THREAD

**Issue by dominicbarnes** [SummitRoute/aws_breaking_changes#5]
This collection of information is extremely useful, thanks for compiling it!

One idea I have would be to expose this as an RSS/Atom feed rather than pure markdown to make it easier to subscribe to these changes as they are reported.

**Comment by 0xdabbad00** [comment]
Looks like one way to do this would be to tag a release every time a need item is added.  Then you can see a feed of releases at https://github.com/SummitRoute/aws_breaking_changes/releases.atom

I can't seem to find a way to get a feed for commits, but I think that might be too noisy due to things like formatting fixes or the "how to check" items being filled in with links.  I think that's the best way for folks.  I can link that feed off the README.md for people unaware. 

Do you think that works?

**Comment by abraithwaite** [comment]
One could also create a github pages formatted repo, and use a jekyll template with basic RSS support.  The added benefit is now there's a pretty site to reference :-)

**Comment by 0xdabbad00** [comment]
I put a link to the releases Atom feed on the Readme  https://github.com/SummitRoute/aws_breaking_changes/commit/018358394837038305f9c635456b1f0d4089ec03
