### ISSUE TITLE
Add rows in reverse order

### ISSUE THREAD

**Issue by AnthonyMastrean** [SummitRoute/aws_breaking_changes#9]
If you're not subscribed to the feed (which doesn't really seem to be setup yet), it's gonna get really annoying scrolling to the bottom of the page to see the "latest" changes. You should think about reversing the order so that the newest changes appear on top.

**Comment by AnthonyMastrean** [comment]
Well, I guess it's not obvious whether the order should be the announced or effective date... hm.

**Comment by 0xdabbad00** [comment]
I am ordering the items that are going to take effect the soonest at the top, so the issue that may impact you first will be the first on the list.  I think this makes the most sense, as some issues don't take effect for a year.  Once the effective date of an issue passes, I plan on removing it from the list after a month (so if your site breaks you have a few weeks to check this to see what might have changed).

Since the initial release, no new issues have been added, so I haven't cut a release yet.  I plan on only creating releases when a new breaking change is identified.  I'll go ahead and do a "first commit" release so people can see their feeds work.
